after_success: bundle exec rake publish_build
script: bundle exec rake test
env:
  global:
  - S3_BUCKET_NAME=builds.emberjs.com
  - secure: Fg6aMd+Th1yEWAdrCfQhKetOcHjqrJwza/4mVV4AGxL/SSY66hr+dun3DnfKJiaCZ95+QEz7EXfXeX6hXEezVXqrSxrtJMh9k9Bq+5bWyBShTwY4KVAbJdOoviqFZ05bEKuaewaiY9j3M6FEOvt0rc7TKBsF2Z9xLqWX0aXZKRQ=
  - secure: TcDVXVYLf5qoSHqCKMDx6sQlaIRjet6LovRLX2X9QBMMA9sSZsbW4SB7Jep8TwtaJZ093bkZwf5lTdzWTd0i9LVdFi95PabxStGMjetiif8HyYCO1hgpHIaKlYkev5I3x733ESiJWMU7UabEjwwN8mDnrR35pI1zKwHVDzFDjhs=
